[versioned] Deal with packages that don't build on system (#996)
## Summary

Fixes a few bugs:

* Remove panic
* If package can't be found for current system, search on all systems so
we can return better error message.
* Don't automatically write to disk when resolving lockfile packages.
That way if there's an error we don't leave the lockfile in a bad state.

## How was it tested?

### package that exists but not for my system

```bash
➜  devbox git:(landau/fix-panic) ✗ devbox add ripgrep@12
There was an error installing nix packages: ripgrep@12. Packages were not added to devbox.json

Error: Package "ripgrep@12" was found, but we're unable to build it for your system. You may need to choose another version or write a custom flake.
```

### package that doesn't exist

```bash
➜  devbox git:(landau/fix-panic) ✗ devbox add foobar1@8

Error: foobar1@8: package not found

To search for packages use https://search.nixos.org/packages
```

### regular versioned install:

```bash
devbox add php@8
```

### Regular install:

```bash
devbox add php
```

### Manual add

* Edited devbox.json and added `php@8` and confirmed lockfile was
updated after `devbox run`