[polish] improve error message for missing devbox-json (#174)
## Summary

The old message was not very nice.


```
> devbox shell empty-projects/no-devbox-json
Error: open /Users/savil/code/jetpack/devbox/testdata/empty-projects/no-devbox-json/devbox.json: no such file or directory
```
or

```
> devbox shell
Error: open devbox.json: no such file or directory
````
## How was it tested?

inside the project directory:
```
➜ devbox shell
Error: No devbox.json found in this directory. Did you run `devbox init` yet?
```

when using a path, print the relative dir:
```
➜ devbox shell empty-projects/no-devbox-json
Error: No devbox.json found in empty-projects/no-devbox-json. Did you run `devbox init` yet?
```